language: c
cache: ccache
branches:
  except:
    - travis

matrix:
 include:
   - os: linux
     dist: trusty
     services: docker

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull vathpela/dbxtool-travis-rawhide:v0 ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run vathpela/dbxtool-travis-rawhide:v0 /bin/sh -c "cd /root/efivar && git fetch && git reset --hard origin/master -- && make clean all install && cd ../dbxtool && git fetch && git reset --hard origin/master -- && ./travis-build.sh --branch $TRAVIS_BRANCH --repo \"$TRAVIS_REPO_SLUG\" --remote \"$TRAVIS_PULL_REQUEST_SLUG\" --pr-sha \"$TRAVIS_PULL_REQUEST_SHA\"" ; fi
